server:
  port: 8088
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/shopapp}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: ${SPRING_REDIS_HOST:locahost}
      port: ${SPRING_REDIS_PORT:6379}
api:
  prefix: api/v1
jwt:
  expiration:
    2592000
    # 30 days 30 * 24 * 60 * 60
  secretKey: YWZmZWN0b3V0c3RvbmVleGNlcHRiZWNhdXNlY29hc3RoYWxmd2F5c2lsa3N0cmlrZXM=
